### ISSUE TITLE
Dataset zip file is broken

### ISSUE THREAD

**Issue by jinlinyi** [jwlee-vcl/CTRL-C#3]
Hi, thank you for the nice work!

The GSV zip file from the gdrive link seems to be broken. Could you help fix that? Thank you!
```
unzip google_street_view_191210.zip
```
```
Archive:  google_street_view_191210.zip
warning [google_street_view_191210.zip]:  611663008 extra bytes at beginning or within zipfile
  (attempting to process anyway)
error [google_street_view_191210.zip]:  start of central directory not found;
  zipfile corrupt.
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)
 ```

**Comment by tosterloh** [comment]
Hey, thanks for excellent work!

I tried to download the GSV zip, but it seems like the link is no longer working. Could you update the link?

**Comment by ZhiguoZhao** [comment]
> Hey, thanks for excellent work!
> 
> I tried to download the GSV zip, but it seems like the link is no longer working. Could you update the link?

Me too

**Comment by yjlee6** [comment]
> > Hey, thanks for excellent work!
> > I tried to download the GSV zip, but it seems like the link is no longer working. Could you update the link?
> 
> Me too

hello, 
Are you fixed it?

**Comment by jwlee-vcl** [comment]
sorry for the late response.
I re-uploaded the zip file.

Here is the link
https://drive.google.com/file/d/1o_831g-3NDnhR94MEwDS2MFvAwpGmVXN/view?usp=drive_link
